server:
  # debug release test
  model: release
  port: 8888
  cors: true
  tls:
    enable: false
    key-file: ./default.key
    cert-file: ./default.pem
  # 机器终端操作回放文件存储路径
  machine-rec-path: ./rec
jwt:
  # jwt key，不设置默认使用随机字符串
  key: 1ec873063dd541868c4bc02dbf97f235
  # 过期时间单位分钟
  expire-time: 1440
# 资源密码aes加密key
aes:
  key: 1ad9a63a27484010885d9a02f04aed25
mysql:
  host: localhost:3366
  username: root
  password: root
  db-name: mayfly-go
  config: charset=utf8&loc=Local&parseTime=true
  max-idle-conns: 5
log:
   # 日志等级, trace, debug, info, warn, error, fatal
  level: info
  # file:
  #   path: ./
  #   name: mayfly.log
